1. Импорт библиотеки NumPy

In [1]:
import numpy as np

2. Примеры создания массивов

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.arange(10, 100, 10)
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
c = np.zeros((3, 5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
d = np.ones((2, 3, 4))
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

3. Демонстрация атрибутов (вывод формы, типов данных)

In [6]:
d.shape # форма

(2, 3, 4)

In [7]:
d.dtype # тип данных

dtype('float64')

In [8]:
d.ndim # размерность пространства

3

In [9]:
c_T = c.transpose() # транспонирование
print(c)
print()
print(c_T)
print()
print(c.shape, c_T.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

(3, 5) (5, 3)


In [10]:
print(b)
print()
b.reshape(3, 3) # изменение формы

[10 20 30 40 50 60 70 80 90]



array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

4. Примеры индексирования и срезов

In [11]:
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
a[4] # обращение к элементу по индексу

np.int64(50)

In [13]:
a[-2] # отрицательный индекс (с конца)

np.int64(80)

In [14]:
a[3:7] # извлечение подмассива с помощью среза

array([40, 50, 60, 70])

In [15]:
a[[3, 7]] # обращение к нескольким элементам по индесам через запятую

array([40, 80])

In [16]:
a[::-1] # от начала до конца с шагом -1 (перевернутый массив)

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

- индексы в многомерных массивах

In [17]:
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
a[2, 3] # обращение к 4 элементу на 3 строке

np.int64(14)

In [19]:
a[(2, 3)] # аналогичная запись

np.int64(14)

In [20]:
a[[2, 3]] # уже берем строки с индексами 2 и 3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
a[[2, 3], 0] # из строк с индесами 2 и 3 берем элемент с индексом 0

array([11, 16])

In [22]:
a[[1,3], [1, 3]] # из строк с индексами 1 и 3 берем элементы с индексами 1 и 3 ( из 2 стр 2 эл, из 4 стр 4 эл)

array([ 7, 19])

In [23]:
a[1:3, :2] # из каждой строки со 2 по 4 не включительно берем элементы с начала по 3 не включительно

array([[ 6,  7],
       [11, 12]])

In [24]:
a[:,2] # все строки, 3 элементы, то есть 3 столбец

array([ 3,  8, 13, 18])

5. Примеры векторных операций и базовых статистик

- векторные операции

In [25]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
a+b # поэлементное сложение

array([11, 22, 33, 44, 55])

In [26]:
a*b # поэлементное умножение

array([ 10,  40,  90, 160, 250])

In [27]:
a**2 # каждый эелемент возводится в степень

array([ 1,  4,  9, 16, 25])

- вычисление базовых статистик

In [28]:
b.min() # минимум

np.int64(10)

In [29]:
b.max() # макмимум

np.int64(50)

In [30]:
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])

In [31]:
a.min(axis=1) # минимум в каждой строке

array([ 1,  6, 11, 16])

In [32]:
a.min(axis=0) # минимум в каждом столбце

array([1, 2, 3, 4, 5])

In [33]:
a.mean() # среднее значение

np.float64(10.5)

In [34]:
a_min = a.min()
a_max = a.max()
norm_a = (a - a_min)/(a_max - a_min) # пример нормализации массива
norm_a

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])